load(file="data/dataTableUnigram.rdata")
load(file="data/dataTableBigram.rdata")
load(file="data/dataTableTrigram.rdata")
load(file="data/dataTableQuadrigram.rdata")
load(file="data/dataTableCinegram.rdata")

load(file="dataPoe/dataTableUnigramPoe.rdata")
load(file="dataPoe/dataTableBigramPoe.rdata")
load(file="dataPoe/dataTableTrigramPoe.rdata")
load(file="dataPoe/dataTableQuadrigramPoe.rdata")
load(file="dataPoe/dataTableCinegramPoe.rdata")
